import os
import sqlite3
from datetime import datetime, timedelta
from typing import Optional, Dict

# Resolve database file path from env (expects format sqlite:///./cookie_share.db)
_DB_URL = os.getenv("DATABASE_URL", "sqlite:///./cookie_share.db")
# Extract path after 'sqlite:///'
_DB_PATH = _DB_URL.replace('sqlite:///', '')

def _get_connection():
    conn = sqlite3.connect(_DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn

def init_db():
    """Create the encrypted_cookies table if it does not exist."""
    with _get_connection() as conn:
        conn.execute('''
            CREATE TABLE IF NOT EXISTS encrypted_cookies (
                id TEXT PRIMARY KEY,
                domain TEXT NOT NULL,
                salt TEXT NOT NULL,
                iv TEXT NOT NULL,
                ciphertext TEXT NOT NULL,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                expires_at TIMESTAMP NOT NULL
            )
        ''')
        conn.commit()

def create_cookie_blob(domain: str, salt: str, iv: str, ciphertext: str, expiry_minutes: int) -> Dict:
    """Insert a new cookie blob and return the row as a dict.
    ``id`` is a UUID generated by SQLite (random). ``created_at`` is set automatically.
    """
    expires_at = datetime.utcnow() + timedelta(minutes=expiry_minutes)
    with _get_connection() as conn:
        cur = conn.execute(
            """
            INSERT INTO encrypted_cookies (id, domain, salt, iv, ciphertext, expires_at)
            VALUES (lower(hex(randomblob(4)) || '-' ||
                     lower(hex(randomblob(2)) ) || '-' ||
                     lower('4' || substr(hex(randomblob(2)),2,3)) || '-' ||
                     lower('8' || substr(hex(randomblob(2)),2,3)) || '-' ||
                     lower(hex(randomblob(6))),
                    ?, ?, ?, ?, ?)
            """,
            (domain, salt, iv, ciphertext, expires_at.isoformat()))
        conn.commit()
        blob_id = cur.lastrowid  # Not the UUID, we need to fetch the inserted row
        row = conn.execute('SELECT * FROM encrypted_cookies WHERE rowid = ?', (blob_id,)).fetchone()
        return dict(row)

def get_cookie_blob(blob_id: str) -> Optional[Dict]:
    """Retrieve a cookie blob; returns None if not found or expired (and deletes it)."""
    with _get_connection() as conn:
        row = conn.execute('SELECT * FROM encrypted_cookies WHERE id = ?', (blob_id,)).fetchone()
        if not row:
            return None
        expires_at = datetime.fromisoformat(row['expires_at'])
        if expires_at < datetime.utcnow():
            # Delete expired record
            conn.execute('DELETE FROM encrypted_cookies WHERE id = ?', (blob_id,))
            conn.commit()
            return None
        return dict(row)

def get_cookie_blob_metadata(blob_id: str) -> Optional[Dict]:
    """Return only non-sensitive metadata (exclude ciphertext, salt, iv)."""
    with _get_connection() as conn:
        row = conn.execute(
            'SELECT id, domain, created_at, expires_at FROM encrypted_cookies WHERE id = ?',
            (blob_id,)
        ).fetchone()
        if not row:
            return None
        # Check expiry
        expires_at = datetime.fromisoformat(row['expires_at'])
        if expires_at < datetime.utcnow():
            conn.execute('DELETE FROM encrypted_cookies WHERE id = ?', (blob_id,))
            conn.commit()
            return None
        return dict(row)

def delete_cookie_blob(blob_id: str) -> bool:
    """Delete a cookie blob; returns True if a row was removed."""
    with _get_connection() as conn:
        cur = conn.execute('DELETE FROM encrypted_cookies WHERE id = ?', (blob_id,))
        conn.commit()
        return cur.rowcount > 0

def delete_expired_cookie_blobs() -> int:
    """Remove all expired blobs; returns the number of rows deleted."""
    now_iso = datetime.utcnow().isoformat()
    with _get_connection() as conn:
        cur = conn.execute('DELETE FROM encrypted_cookies WHERE expires_at < ?', (now_iso,))
        conn.commit()
        return cur.rowcount

# Initialize the database schema on import
init_db()
